### ISSUE TITLE
2020 / Windows 10 --> Camera Name not found

### ISSUE THREAD

**Issue by POD-io** [marcelebrate/Microsoft-LifeCam-Settings-Tool#2]
Hello,

I know this is quite a stretch commenting 5 years outside of when this was made, but I used it many years back with great success. My issue in 2020 is only that when I run the .exe I am getting "ERROR: Camera "Microsoft LifeCam" not found Skipping."

This happens for every name I use, and I've confirmed them in my device manager, as well as my LifeCam program.

Thanks for any help!

**Comment by marcelray** [comment]
Yeah, unfortunately I don't have access to a LifeCam camera anymore (or any USB camera) so I won't be able to help much. I'm sure enough has changed since Windows 7 that this won't work out of the box. Have you checked any of the forks from my project? It looks like there are several people who've been using it recently: [https://github.com/marcelray/lifecam-settings/network/members](https://github.com/marcelray/lifecam-settings/network/members)

**Comment by POD-io** [comment]
Ooohhhh cheers! Not super familiar with GitHub, so never knew forks were a
thing. Gonna check those out.

Thanks so much!

**Comment by marcelray** [comment]
No problem. Hope you find something that works!
